/*
 * Copyright (c) 2019. All rights reserved.
 *
 * @author Pieter De Clercq
 *
 * https://github.com/thepieterdc/random-java
 */
package io.github.thepieterdc.random;

import java.util.Collection;
import java.util.HashSet;
import java.util.Random;

/**
 * An abstract random generator.
 */
public abstract class AbstractRandomGenerator<T> implements RandomGenerator<T> {
	protected final Random rng;
	
	/**
	 * AbstractRandomGenerator constructor.
	 *
	 * @param seed the random seed
	 */
	protected AbstractRandomGenerator(final long seed) {
		this.rng = new Random(seed);
	}
	
	/**
	 * AbstractRandomGenerator constructor.
	 */
	protected AbstractRandomGenerator() {
		this.rng = new Random();
	}
	
	@Override
	public Collection<T> generate(int amount, int maxTries) {
		if (amount < 0) {
			throw new IllegalArgumentException("The amount of values to generate must be greater than zero.");
		}
		
		if (amount > this.getCapacity()) {
			throw new IllegalArgumentException(
				String.format("At most %d distinct random values can be generated by this generator.", amount)
			);
		}
		
		final Collection<T> ret = new HashSet<>(amount);
		
		int tries = 0;
		
		while (ret.size() < amount && tries < maxTries) {
			ret.add(this.generate());
			tries++;
		}
		return ret;
	}
}
