name: Java

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build on jdk ${{ matrix.java }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        java: [11.x.x, 12.x.x, 15.x.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java}}
      - name: Cache the dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload the coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
