name: Publish release

on:
  push:
    branches:
      - release

jobs:
  docs:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: 17
          server-id: github
          server-password: GITHUB_TOKEN
      - name: Cache the dependencies
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Generate the documentation
        run: mvn --batch-mode javadoc:javadoc
      - name: Publish the documentation
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: gh-pages
          folder: docs/apidocs

  publish:
    name: Publish artifact to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: 17
          server-id: github
          server-password: GITHUB_TOKEN
      - name: Configure git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Cache the dependencies
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get the release version
        id: version
        run: |
          VERSION_RAW=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION="${VERSION_RAW//-SNAPSHOT/}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Publish package
        run: mvn --batch-mode release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        run: gh release create "$VERSION" --title "$VERSION" --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
      - name: Open a pull request
        run: |
          gh pr create \
            --base master \
            --head release \
            --assignee thepieterdc \
            --title "Release $VERSION" \
            --body "Merge the maven release commits into the main branch."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
